version: '3'
services:
  secure-rabbitmq:
    image: rabbitmq:3-management
    ports:
      - 15673:15672
      - 5673:5672
    environment: 
      RABBITMQ_DEFAULT_PASS: pass
      RABBITMQ_DEFAULT_USER: user
